### ISSUE TITLE
commands take long time to finish after upgrade to node 17.0.1

### ISSUE THREAD

**Issue by galak** [joelpurra/uvcc#20]
Doing a command like:

```
kumar-macair:~ galak$ uvcc --verbose devices
Parsed arguments: {
  "address": 0,
  "cmd": "devices",
  "product": 0,
  "values": [],
  "vendor": 0,
  "verbose": true
}
[
  {
    "name": "HD Pro Webcam C920",
    "vendor": 1133,
    "product": 2194,
    "address": 5
  }
]
```

It will quickly report the output and than pause for 7-8 seconds before returning to prompt.

**Comment by joelpurra** [comment]
@galak: at this time it's unfortunately expected, due to the upstream delay fix in `node-usb` v1.8.0 being reverted in `node-usb` v1.9.1 as it caused other issues with Node.js.

The upstream error hasn't been fully resolved; I had a look a while ago but didn't find/fix the underlying issue. All `uvcc` users are [encouraged to help out in `node-usb`](https://github.com/node-usb/node-usb) so this can be fixed!

See

- #16: your original report, related to `node-usb` v1.7.0; `uvcc` pinned to `node-usb` v1.6.5.
- #18: required Node.js v17 compatibility upgrade to `node-usb` v1.8.0+, which reintroduces delays.
- #19: Pin to `node-usb` v1.8.0, since the delay fix in v1.8.1/v1.9.0 causes crashes.
.

**Comment by wookayin** [comment]
The previous versions worked fine. Is downgrading node the only workaround?

**Comment by joelpurra** [comment]
Just released `uvcc` v5.0.2, targeting [`node-usb` v1.9.2](https://github.com/node-usb/node-usb/releases/tag/v1.9.2). This version [includes an upstream fix for the exit delay](https://github.com/node-usb/node-usb/pull/460).

Install/upgrade with:

```shell
npm install --global uvcc@latest
```

I'll close this issue as fixed. Please confirm whether the fix works, or not!

**Comment by wookayin** [comment]
With uvcc@5.0.2, usb@2.1.3, node v17.3.0, this is happening again. Should I file a new issue?

**Comment by joelpurra** [comment]
@wookayin: yes, please!
